### ISSUE TITLE
React import as `.tsx`

### ISSUE THREAD

**Issue by ewilan-riviere** [unjs/listhen#110]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Package Manager:  pnpm@8.6.12
- h3 version: 1.8.0
- listhen version: 1.3.0

### Reproduction

I create a stackblitz project <https://stackblitz.com/github/kiwilan/feed-renderer>

But to have better reproduction, just clone repository

```bash
git clone https://github.com/kiwilan/feed-renderer.git
cd feed-renderer
pnpm i
pnpm dev
```

### Describe the bug

When we use `pnpm dev` shortcut for `listhen -w ./src/index.ts`, the output will be

```bash
 ERROR  Cannot find module './podcast-renderer'                                                                                                                           listhen 1:44:09 PM
Require stack:
- ./feed-render/src/react/index.ts

  - ./src/react/index.ts
  at ./src/react/index.ts:1:309
  at ./src/models/Podcast.ts:2:14
```

The error comes from `src/react/index.ts` with an import

```ts
import PodcastRenderer from './podcast-renderer'
```

The file is `src/react/podcast-renderer.tsx`, a simple React file.

## Alternative

If I use `tsx` with...

```bash
pnpm dev:node
```

...everything works.

So I think `listhen` could have a problem with React import with `-w` flag?

## Build

When I build app with `tsup`

```bash
pnpm build
pnpm start
```

I have no error and React component is correctly imported.

### Additional context

Error import could have another origin but I try many solutions and `listhen` could be cause.

**Comment by pi0** [comment]
Hi. JSX/TSX support is underway for jiti (the runtime library that powers listhen's ts support). You can follow up from here: https://github.com/unjs/jiti/issues/138

**Comment by ewilan-riviere** [comment]
Thanks you!

**Comment by ewilan-riviere** [comment]
From <https://github.com/unjs/jiti/issues/138>, I try other solutions and render functions work well. All files are `.ts`, I just add `vue` as dependency and use `h` function to create elements. It's really amazing and more simple than my first solution with React. I can load CSS file with `fs.readFile()` and inject it into `head` element.

```ts
import { defineProps, h } from 'vue'
import head from './head'
import header from './header'
import type { Podcast } from '~/models/Podcast'

interface Props {
  podcast: Podcast
  css?: string
}

export default {
  props: defineProps<Props>(),
  setup(props: Props) {
    return h('html', [
      head.setup({ title: props.podcast.title, css: props.css }),
      h('body', [
        header.setup({ podcast: props.podcast }),
      ]),
    ])
  },
}
```

Of course I can render it to HTML with `renderToString()` from `vue/server-renderer`. I don't need react anymore.
If someone is interested, you can check the code here: <https://github.com/kiwilan/feed-renderer/tree/8c34378ca7a78ee00af7d1bfef7222c6447c1306/src/components>

Thanks again!

**Comment by pi0** [comment]
Nice finding! Let's keep it open. I think we can improve example and docs!
