### ISSUE TITLE
Invalid handler. It should be a function

### ISSUE THREAD

**Issue by edimitchel** [unjs/listhen#92]
### Environment

h3 `1.8.0-rc.2` and `1.8.0-rc.3`
OSX, with pnpm 8.6

### Reproduction

https://stackblitz.com/edit/github-uqdf6b?file=package.json

### Describe the bug

_The issue occurred when I tried to illustrate [a feature request](https://github.com/unjs/h3/issues/488)._

When I use listhen since h3 was added with the rc version (the 2nd), I got this following issue:

>  ERROR  Invalid handler. It should be a function:  

Code:
```ts
app.use(
  '/api',
  eventHandler((event) =>
    proxyRequest(event, join(BACKEND_ENDPOINT, event.path))
  )
);
```

### Additional context

According to the error message, it is linked with `fromNodeMiddleware`.

Here the trace from the function (in h3):

```
    at fromNodeMiddleware (file:///Users/micheledighofffer/DEV/listhen/node_modules/.pnpm/h3@1.8.0-rc.3/node_modules/h3/dist/index.mjs:1840:31)
    at loadHandle (file:///Users/micheledighofffer/DEV/listhen/dist/index.mjs:892:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async listenAndWatch (file:///Users/micheledighofffer/DEV/listhen/dist/index.mjs:998:3)
    at async Object.run (file:///Users/micheledighofffer/DEV/listhen/dist/cli.mjs:91:7)
    at async runCommand (file:///Users/micheledighofffer/DEV/listhen/node_modules/.pnpm/citty@0.1.2/node_modules/citty/dist/index.mjs:313:5)
    at async runMain (file:///Users/micheledighofffer/DEV/listhen/node_modules/.pnpm/citty@0.1.2/node_modules/citty/dist/index.mjs:425:7)
```
The function is [called by listhen](https://github.com/unjs/listhen/blob/43e0a3c190b83273099941f1938cee45ec3ee832/src/server/dev.ts#L126) even it's not use in the app.

It seems that the type is not the one expected and doesn't match the change made by @danielroe (7e9570)
The handler type is not function but object.

**Comment by pi0** [comment]
better error in the next version:

<img width="823" alt="image" src="https://github.com/unjs/listhen/assets/5158436/bc7f089c-8e71-450e-b92a-ba2520e0a452">


<img width="498" alt="image" src="https://github.com/unjs/listhen/assets/5158436/a26885fe-0cf5-4505-bb8d-9f68d51fc0ba">
